SumoLogic/sumologic-kubernetes-fluentd

.github/workflows/pull_requests.yml
Dockerfile

Backport https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/118

Use numeric user ID

---

Dockerfile

This is related to https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1461

Update linux-libc-dev to include security fixes

---

fluent-plugin-kubernetes-sumologic/README.md

Added missing information about plugin configuration.

docs: Update README on kubernetes_sumologic plugin

---

fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_service_monitor.rb

Found a commented-out test, uncommented it, it's passing.

test: Uncomment a commented-out test

---

.gitignore
README.md
Vagrantfile
vagrant/README.md
vagrant/provision.sh

Add vagrant to the repository

---

Dockerfile

Fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1614

chore(deps): update rdoc to mitigate CVE in 6.1.2

---

Dockerfile
fluent-plugin-datapoint/Gemfile.lock
fluent-plugin-datapoint/fluent-plugin-datapoint.gemspec
fluent-plugin-enhance-k8s-metadata/Gemfile.lock
fluent-plugin-enhance-k8s-metadata/fluent-plugin-enhance-k8s-metadata.gemspec
fluent-plugin-events/Gemfile.lock
fluent-plugin-events/fluent-plugin-events.gemspec
fluent-plugin-kubernetes-metadata-filter/Gemfile.lock
fluent-plugin-kubernetes-metadata-filter/fluent-plugin-kubernetes-metadata-filter.gemspec
fluent-plugin-kubernetes-sumologic/Gemfile.lock
fluent-plugin-kubernetes-sumologic/fluent-plugin-kubernetes-sumologic.gemspec
fluent-plugin-prometheus-format/Gemfile.lock
fluent-plugin-prometheus-format/fluent-plugin-prometheus-format.gemspec
fluent-plugin-protobuf/Gemfile.lock
fluent-plugin-protobuf/fluent-plugin-protobuf.gemspec

See individual commits for details.

fix(deps): Update system packages and gems to fix vulnerabilities

---

.github/workflows/dev_builds.yml
.github/workflows/pull_requests.yml
.github/workflows/release_builds.yml
Makefile
alpine.Dockerfile
fluent-plugin-protobuf/Gemfile.lock
fluent-plugin-protobuf/fluent-plugin-protobuf.gemspec
fluent.conf

This is mostly to get rid of the vulnerabilities that the Debian image carries with it.

feat: Add Alpine-based image

---

fluent-plugin-enhance-k8s-metadata/README.md
fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb

Tests will be added separately

feat(enhance_k8s_metadata): add `add_service` option

---

Dockerfile
alpine.Dockerfile

Including:
- bundler: CVE-2021-43809
- cgi: CVE-2021-41816
- date: CVE-2021-41817
- rdoc: CVE-2021-31799
- rexml: CVE-2021-28965

fix: update gems to prevent vulnerabilities

---

.github/dependabot.yml
Dockerfile
alpine.Dockerfile
fluent-plugin-protobuf/Gemfile.lock

See the individual commits for details.

fix: fix vulnerabilities

---

Makefile

add build-plugins target to Makefile

chore(makefile): add build-plugins target

---

Dockerfile
alpine.Dockerfile

Changed:
- https://github.com/SumoLogic/fluentd-output-sumologic/pull/75

chore: bump sumologic_output plugin to 1.7.5

---

Dockerfile
alpine.Dockerfile

Signed-off-by: Dominik Rosiek <drosiek@sumologic.com>

chore(fluent-plugin-sumologic_output): upgrade to 1.8.0

---

CONTRIBUTING.md
docs/release.md

Signed-off-by: Dominik Rosiek <drosiek@sumologic.com>

doc(release): add release document

---

fluent-plugin-kubernetes-sumologic/README.md

docs: update documentation about Pod annotations which can be used to override plugin settings
add documentation for "sumologic.com/format", "sumologic.com/sourceName", "sumologic.com/sourceHost"

docs: update documentation about Pod annotations

---

Dockerfile
alpine.Dockerfile

Signed-off-by: Dominik Rosiek <drosiek@sumologic.com>

fix(docker): use proper kubeclient revision

---

ci/build-push-multiplatform.sh

job that passed: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/actions/runs/5644328166/job/15287893723

fix(ci): fix creating tag for docker image

---

alpine.Dockerfile

This fixes failing runs for Alpine.

fix: set async version in Dockerfile for Alpine

---

fluent-plugin-kubernetes-sumologic/Gemfile
fluent-plugin-kubernetes-sumologic/Gemfile.lock
fluent-plugin-kubernetes-sumologic/fluent-plugin-kubernetes-sumologic.gemspec
fluent-plugin-kubernetes-sumologic/test/helper.rb

chore: remove simplecov
