SumoLogic/sumologic-kubernetes-fluentd

.github/dependabot.yml

Based on https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates#disabling-dependabot-version-updates, let's see if it works.

Make Dependabot leave ruby at 2.6.x

---

fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
fluent-plugin-enhance-k8s-metadata/test/plugin/test_filter_enhance_k8s_metadata.rb

The `@pods_to_services` variable is being initialized in another thread https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/main/fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/service_monitor.rb#L52. We need to make sure `@pods_to_services` is not accessed until it's properly initialized.

Prevent access to uninitialized variable

---

Dockerfile

Let's wait for the Docker Hub image before merging:
https://hub.docker.com/r/fluent/fluentd/tags?page=1&ordering=last_updated&name=1.12

Upgrade FluentD version to 1.12

---

Dockerfile
fluent-plugin-enhance-k8s-metadata/Gemfile
fluent-plugin-enhance-k8s-metadata/Gemfile.lock
fluent-plugin-enhance-k8s-metadata/fluent-plugin-enhance-k8s-metadata.gemspec
fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/connector.rb
fluent-plugin-events/Gemfile
fluent-plugin-events/Gemfile.lock
fluent-plugin-events/fluent-plugin-events.gemspec
fluent-plugin-events/lib/sumologic/kubernetes/connector.rb
fluent-plugin-kubernetes-metadata-filter/Gemfile
fluent-plugin-kubernetes-metadata-filter/Gemfile.lock
fluent-plugin-kubernetes-metadata-filter/fluent-plugin-kubernetes-metadata-filter.gemspec
fluent-plugin-kubernetes-metadata-filter/lib/fluent/plugin/filter_kubernetes_metadata.rb

The Fluentd plugins we use make a good amount of HTTP connections to the Kubernetes API server for Kubernetes metadata enrichment. Until now, the HTTP connections were being closed after each HTTP request, requiring a new HTTP connection to be established on every request to API server. This was a suboptimal solution, and the root cause for SNAT port exhaustion in AKS clusters.
With this change, we are using a yet unreleased version of [Kubeclient](https://github.com/abonas/kubeclient/) library to be able to create persistent HTTP connections. The Kubeclient library (which is used by our Fluentd plugins to make requests to k8s API server) originally used [RestClient](https://github.com/rest-client/rest-client/) gem under the hood, which does not make it possible to create persistent …

 Make connections to k8s API server persistent

---

test/test_docker.rb

When testing with `make image-test`, it was not possible to override the image tag,
as it was hardcoded as `latest`.
With this change, it's possible to override the image name _and_ its tag, with e.g.:
```shell
make image-test IMAGE_NAME=fluentd:custom
```

test: Make it easier to override tested image name

---

Dockerfile

When one uses this image in k8s cluster with a security context having `runAsNonRoot` set to `true` the following error is can be seen:
```
Error: container has runAsNonRoot and image has non-numeric user (fluent), cannot verify user is non-root
```
This patch fixes that by using a numeric user ID.

Use numeric user ID

---

fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb

Its usage removed in https://github.com/SumoLogic/fluentd-kubernetes-sumologic/pull/100/files#diff-1fc38bd8e213be969cd4f1128a8396ecb961769e1b3568c6a25638effe405567L125

refactor: Remove unused method

---

fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb
fluent-plugin-kubernetes-sumologic/test/plugin/test_filter_kubernetes_sumologic.rb

This adds two new annotations:
- `sumologic.com/sourceCategoryPrefix`
- `sumologic.com/sourceCategoryReplaceDash`
The documentation for these new annotations was already added in previous commit 🔀

Add source category prefix and replace dash annotations

---

.github/dependabot.yml
Dockerfile
fluent-plugin-protobuf/Gemfile.lock
fluent-plugin-protobuf/fluent-plugin-protobuf.gemspec

Due to higher CPU usage on Fluentd metrics pods.

Downgrade google-protobuf to 3.9.2

---

fluent-plugin-protobuf/lib/fluent/plugin/parser_protobuf.rb

If log level is higher than trace, trace log messages should not be evaluated.

fix: Only evaluate logging expressions when needed

---

fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/service_monitor.rb
fluent-plugin-enhance-k8s-metadata/test/resources/endpoints_list.json
fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_service_monitor.rb

fix: Fix duplicated service names in metrics metadata

---

vagrant/provision.sh

Install bundler for vagrant user (it has been installed for root previously)

vagrant: fix bundler installation for vagrant user

---

.github/workflows/dev_builds.yml
.github/workflows/release_builds.yml
Dockerfile
Makefile
README.md
ci/build-push-multiplatform.sh

I wanted to achieve the following goals with this PR:
- Build Fluentd images for all platforms (amd64, arm, arm64) and push them to container registry under a common tag,
- Use single Dockerfile for all platforms, preventing duplication,
- Make it possible (and easy) to build the multi-platform image locally and push it to a custom registry.

feat: Build images for ARM

---

.github/workflows/dev_builds.yml
Makefile

A separate AWS account has been created for Sumo Logic's opensource artifacts.
During the transition period, we want to push images to both registries - the original and the opensource one.

ci: Push images to ECR in opensource account

---

.github/dependabot.yml

Due to a recent change in how Dependabot schedules updates, the `time` and `timezone` entries are no longer needed.
See https://github.blog/changelog/2021-06-16-dependabot-now-schedules-version-updates-uniformly/.

ci(dependabot): Simplify update schedule

---

Dockerfile

The `ruby:2.6.8` image tag was changed some hours ago by the Ruby team to be based on Debian 11 `bullseye` instead of Debian 9 `stretch`. This caused native dependency errors from `ffi` gem.
This change updates the base image for the builder image to `ruby:2.6.8-buster` to avoid the ffi error. It also matches the Fluentd image, which is also based on `buster`.

fix: Use Buster-based Ruby for builder image

---

alpine.Dockerfile

Adds gems that exist in the upstream Fluentd image
at https://github.com/fluent/fluentd-docker-image/blob/209628f474f60bc6ff05c8c1ab8ca06dd538c44d/v1.12/alpine/Dockerfile#L22-L28.
Not including resolv:0.2.1, because I believe
it's already bundled with Ruby 2.6.8.

fix(alpine): Add missing gems

---

fluent-plugin-prometheus-format/README.md
fluent-plugin-prometheus-format/lib/fluent/plugin/filter_prometheus_format.rb
fluent-plugin-prometheus-format/test/plugin/test_filter_prometheus_format.rb
fluent-plugin-prometheus-format/test/resources/datapoint.empty.json
fluent-plugin-prometheus-format/test/resources/output.datapoint.empty.json

Before this change, this plugin would fail on an event with a field that has value `null`.
The reason was that the `escape` method assumes the value is not null.

fix(prometheus_format): ignore fields with null value

---

fluent-plugin-enhance-k8s-metadata/README.md
fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/service_monitor.rb

This reverts commit 0abdce18db3c60f198f38a5da0196f7ff6147c5b.
Disabling watching in the `enhance_k8s_metadata` plugin causes the `service` label to be missing.

Revert "feat(enhance_k8s_metadata): add `watch` option"

---

fluent-plugin-enhance-k8s-metadata/README.md
fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/connector.rb
fluent-plugin-events/README.md
fluent-plugin-events/lib/fluent/plugin/in_events.rb
fluent-plugin-events/lib/sumologic/kubernetes/connector.rb
fluent-plugin-kubernetes-metadata-filter/README.md
fluent-plugin-kubernetes-metadata-filter/lib/fluent/plugin/filter_kubernetes_metadata.rb

Three plugins make connections to the Kubernetes API server:
- enhance_k8s_metadata
- events
- kubernetes_metadata
All of those by default make persistent connections to the Kubernetes API server.
This change exposes a new `keepalive` option that allows to change it.

feat: expose `keepalive` option to disable persistent connections to API server

---

.github/dependabot.yml

Apparently the existing ignore config does not work,
because Dependabot created a 2.7.x update for Ruby: #367.
Let's see if a taking different approach helps.

ci(dependabot): change ignore config for Docker

---

fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/cache_strategy.rb
fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_cache_strategy.rb

There's no reason to keep keys for pods which don't exist anymore and unnecessarily spam the API Server. Should fix #
Move the cache refresh logic to the CacheStrategy, which is the more natural place for it, and makes it easier to test.

fix(enhance_k8s_metadata): remove nonexistent pods on cache refresh

---

.github/dependabot.yml

Apparently there was a typo in the config which went unnoticed until now.
https://github.com/SumoLogic/sumologic-kubernetes-fluentd/runs/4978597076
```
Dependabot encountered the following error when parsing your .github/dependabot.yml:
The property '#/updates/1/ignore/0/update-types/0' value "version-update:semver:major" did not match one of the following values: version-update:semver-major, version-update:semver-minor, version-update:semver-patch
The property '#/updates/1/ignore/0/update-types/1' value "version-update:semver:minor" did not match one of the following values: version-update:semver-major, version-update:semver-minor, version-update:semver-patch
Please update the config file to conform with Dependabot's specification.
```

ci: fix Dependabot config for Docker

---

fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/reader.rb

There is nothing to warn about.
This warning does not signify a potentially dangerous situation.

fix(enhance_k8s_metadata): remove "not supported resource" warning

---

Dockerfile
alpine.Dockerfile

See: https://github.com/SumoLogic/fluentd-output-sumologic/releases/tag/1.7.4. The only change is logging receiver warnings.

chore: bump the Sumo output plugin to 1.7.4

---

Dockerfile
Vagrantfile
alpine.Dockerfile
fluent-plugin-datapoint/Gemfile.lock
fluent-plugin-datapoint/fluent-plugin-datapoint.gemspec
fluent-plugin-enhance-k8s-metadata/Gemfile.lock
fluent-plugin-enhance-k8s-metadata/fluent-plugin-enhance-k8s-metadata.gemspec
fluent-plugin-events/Gemfile.lock
fluent-plugin-events/fluent-plugin-events.gemspec
fluent-plugin-kubernetes-metadata-filter/Gemfile.lock
fluent-plugin-kubernetes-metadata-filter/fluent-plugin-kubernetes-metadata-filter.gemspec
fluent-plugin-kubernetes-sumologic/Gemfile.lock
fluent-plugin-kubernetes-sumologic/fluent-plugin-kubernetes-sumologic.gemspec
fluent-plugin-prometheus-format/Gemfile.lock
fluent-plugin-prometheus-format/fluent-plugin-prometheus-format.gemspec
fluent-plugin-protobuf/Gemfile.lock
fluent-plugin-protobuf/fluent-plugin-protobuf.gemspec

- chore: change Vagrant IP address for vbox 6.1.28 compat
- chore: bump Fluentd to v1.14.6

 chore: bump Fluentd to v1.14.6 

---

CONTRIBUTING.md
fluent-plugin-enhance-k8s-metadata/Gemfile
fluent-plugin-enhance-k8s-metadata/Gemfile.lock
fluent-plugin-events/Gemfile
fluent-plugin-events/Gemfile.lock
fluent-plugin-kubernetes-metadata-filter/Gemfile
fluent-plugin-kubernetes-metadata-filter/Gemfile.lock

The updated version contains https://github.com/ManageIQ/kubeclient/pull/567

fix: fix reloading bearer token file by using the newest kubeclient

---

.github/workflows/pull_requests.yml
CONTRIBUTING.md
Dockerfile
Makefile
alpine.Dockerfile
ci/build-push-multiplatform.sh
fluent-plugin-datapoint/.bundle/config
fluent-plugin-datapoint/Gemfile.lock
fluent-plugin-datapoint/fluent-plugin-datapoint.gemspec
fluent-plugin-enhance-k8s-metadata/.bundle/config
fluent-plugin-enhance-k8s-metadata/Gemfile.lock
fluent-plugin-enhance-k8s-metadata/fluent-plugin-enhance-k8s-metadata.gemspec
fluent-plugin-events/.bundle/config
fluent-plugin-events/Gemfile.lock
fluent-plugin-events/fluent-plugin-events.gemspec
fluent-plugin-kubernetes-metadata-filter/.bundle/config
fluent-plugin-kubernetes-metadata-filter/Gemfile.lock
fluent-plugin-kubernetes-metadata-filter/fluent-plugin-kubernetes-metadata-filter.gemspec
fluent-plugin-kubernetes-sumologic/.bundle/config
fluent-plugin-kubernetes-sumologic/Gemfile.lock
fluent-plugin-kubernetes-sumologic/fluent-plugin-kubernetes-sumologic.gemspec
fluent-plugin-prometheus-format/.bundle/config
fluent-plugin-prometheus-format/Gemfile.lock
fluent-plugin-prometheus-format/fluent-plugin-prometheus-format.gemspec
fluent-plugin-protobuf/.bundle/config
fluent-plugin-protobuf/Gemfile.lock
fluent-plugin-protobuf/fluent-plugin-protobuf.gemspec
vagrant/provision.sh

This also upgrades:
- Ruby from v2.7 to v3.1
- Alpine from 3.14 to 3.16
and some other packages. See the Dockerfiles for details.

chore: upgrade Fluentd to v1.15.3

---

ci/build-push-multiplatform.sh

The failing task already passed on https://github.com/SumoLogic/sumologic-kubernetes-fluentd/actions/runs/4565500819
The workflow corresponding to this branch: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/actions/runs/4565813000

fix(ci): fix failing image builds

---

.github/workflows/release_builds.yml

remove set-output based on https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix deprecations in github actions

---

fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
fluent-plugin-events/lib/fluent/plugin/in_events.rb

Fixes two cases where `KUBERNETES_SERVICE_HOST` is used without proper handling for it potentially being an IPv6 address. The changes are derived from the third case in [fluent-plugin-kubernetes-metadata-filter/lib/fluent/plugin/filter_kubernetes_metadata.rb](https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blame/dfb5d5d6b24b1e4ff7dd8ac094e3ad8c7d482720/fluent-plugin-kubernetes-metadata-filter/lib/fluent/plugin/filter_kubernetes_metadata.rb#L175-L187) where IPv6 is handled properly.

Handle IPv6 KUBERNETES_SERVICE_HOST

---

fluent-plugin-kubernetes-sumologic/Gemfile.lock
fluent-plugin-kubernetes-sumologic/fluent-plugin-kubernetes-sumologic.gemspec

Fixes vulnerability in yajl-ruby v1.4.2.
Refs: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/security/dependabot/17

fix(security): bump yajl-ruby to v1.4.3

---

fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
fluent-plugin-events/lib/fluent/plugin/in_events.rb

Reverts SumoLogic/sumologic-kubernetes-fluentd#437
This change doesn't work, function `present?` is not defined.

Revert "Handle IPv6 KUBERNETES_SERVICE_HOST"
